"""changed column in user

Revision ID: 29d30b487935
Revises: 9fb494ae86ea
Create Date: 2023-10-22 14:12:01.569209

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '29d30b487935'
down_revision: Union[str, None] = '9fb494ae86ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
