"""test

Revision ID: 2d572bc6985e
Revises: c23765d7751d
Create Date: 2023-10-07 10:51:19.610130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models import DatabaseModel


# revision identifiers, used by Alembic.
revision: str = '2d572bc6985e'
down_revision: Union[str, None] = 'c23765d7751d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'name')
    op.drop_column('images', 'desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('desc', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('images', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
