"""remove useless mixins

Revision ID: 73f9fba68150
Revises: 811682d1a2e8
Create Date: 2023-12-03 16:39:09.754939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73f9fba68150'
down_revision: Union[str, None] = '811682d1a2e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('link', sa.VARCHAR(length=200), nullable=False))
    op.drop_column('images', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('content', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('images', 'link')
    # ### end Alembic commands ###
