"""Fix greenlet errors by changing lazy loading strategy

Revision ID: 9a2d63fcef75
Revises: 67b103c1922d
Create Date: 2023-12-29 15:44:21.287887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models import DatabaseModel


# revision identifiers, used by Alembic.
revision: str = '9a2d63fcef75'
down_revision: Union[str, None] = '67b103c1922d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
