"""changed column name

Revision ID: baa545f90eda
Revises: b3c6af0b887a
Create Date: 2023-12-22 12:44:47.195513

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baa545f90eda'
down_revision: Union[str, None] = 'b3c6af0b887a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('link', sa.VARCHAR(length=200), nullable=False))
    op.drop_column('images', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('content', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('images', 'link')
    # ### end Alembic commands ###
