"""test

Revision ID: c23765d7751d
Revises: d97b8b00c58f
Create Date: 2023-10-07 10:43:00.454703

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c23765d7751d'
down_revision: Union[str, None] = 'd97b8b00c58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('content', sa.LargeBinary(), nullable=False))
    op.drop_column('images', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('link', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_column('images', 'content')
    # ### end Alembic commands ###
